### ISSUE TITLE
Community member shared a bug

### ISSUE THREAD

**Issue by bwsw** [bwsw/cloudstack-ui#94]
It seems, that it's Safari. 
I don't see exactly, but link is here: https://box.bw-sw.com/f/a097ca3781/?raw=1

Let's try to find it.

**Comment by wowshakhov** [comment]
solved in master

**Comment by karuturi** [comment]
Its google chrome. @wowshakhov is docker container updated with latest?

**Comment by bwsw** [comment]
@karuturi, Yes it should be in docker hub already. Just pull latest. Write me if it still has problems.

**Comment by karuturi** [comment]
I pulled the latest. Still facing the same problem. (tried on firefox as well and same issue)

**Comment by karuturi** [comment]
Is the fix for this in PR #92 ? 
I dont think the js on my local app reflects the new js added in that PR. (here is the js code I see https://gist.github.com/karuturi/3a2bddbeb047a4bd46c2c32e2d8e5a03 )

**Comment by bwsw** [comment]
@karuturi 
What version of ACS you are using?
Is it simulator or real deployment?

**Comment by karuturi** [comment]
simulator and ACS master(4.10)

**Comment by bwsw** [comment]
@karuturi 
Do you have a guide how to deploy it and test against it? Since, we are developing and testing against real deploment of ACS 4.9.2.

**Comment by karuturi** [comment]
These are the steps I followed on mac

1. git checkout master
2. mvn clean install -Pdeveloper,systemvm -Dsimulator -DskipTests=true
3. mvn  -Pdeveloper -pl developer -Ddeploydb
4. mvn  -Pdeveloper -pl developer -Ddeploydb-simulator
5. mvn -pl client jetty:run -Dsimulator
6. docker pull bwsw/cloudstack-ui
7. docker run -d -p 80:80 --name cloudstack-ui -e API_BACKEND_URL=http://localhost:8096/client/api bwsw/cloudstack-ui

**Comment by bwsw** [comment]
@karuturi cool, we the code test against it.
@wowshakhov take a look.

**Comment by bwsw** [comment]
@karuturi 
Try to specify API_BACKEND_URL to host ip, not to **localhost**, I suppose it may be the problem the bootstrap code inside the docker doesn't see **localhost**.

**Comment by karuturi** [comment]
yes. thats the issue. thank you. It obviously cant see localhost. I feel stupid now -_-

**Comment by karuturi** [comment]
Can I suggest for a better error message when it cant reach the cloudstack endpoint?

**Comment by bwsw** [comment]
@karuturi 
Probably, such improvement is good and meaningful)
also, don't add /client/api to ip (i suppose it's a buggy way, and request to change it). So, basically we put in a backlog two things based on your issue:

- better diagnosis during container bootstrap
- remove automatic "/client/api" addition by the bootstrap code.

**Comment by karuturi** [comment]
superb. thanks.

**Comment by bwsw** [comment]
Moved to #101. The issue is closed.
